version: '3.7'

services:
  prometheus: 
    image: prom/prometheus:latest
    container_name: prometheus
    depends_on:
      - nodeexporter
    #  - cadvisor
    ports:
      - 8082:9090
    volumes:
      - prometheus_data:/prometheus
      - /home/azureuser/CloudVorlesung/Monitoring/config.yaml:/etc/prometheus/prometheus.yml
    user: "root"
    restart: always
    environment:
      TZ: ${TZ}
    networks:
      - default

  nodeexporter:
    image: prom/node-exporter:latest
    container_name: node_exporter
    restart: always
    ports:
      - 8083:9100
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--path.rootfs=/rootfs'
      - '--collector.filesystem.ignored-mount-points="^(/rootfs|/host|)/(sys|proc|dev|host|etc)($$|/)"'
      - '--collector.filesystem.ignored-fs-types="^(sys|proc|auto|cgroup|devpts|ns|au|fuse\.lxc|mqueue)(fs|)$$"'
    environment:
      TZ: ${TZ}
    #labels:
    #    com.centurylinklabs.watchtower.enable: "true"
    networks:
      - default
    
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor
    restart: always
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    environment:
      TZ: ${TZ}
    command:
      - --housekeeping_interval=15s
      - --global_housekeeping_interval=15s
      - --docker_only=true
      - --disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl
    #labels:
    #    com.centurylinklabs.watchtower.enable: "true"
    networks:
      - default
  
  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    depends_on:
      - prometheus
    ports:
      - 8084:3000
    restart: always
    volumes:
      - grafana_data:/var/lib/grafana
    user: "1000" # USER ID des Docker Users anpassen
    environment:
      - TZ= ${TZ}
    #  - GF_SMTP_ENABLED=true
    #  - GF_SMTP_HOST=mx.yourdomain.tld:465
    #  - GF_SMTP_USER=monitoring@yourdomain.tld
    #  - GF_SMTP_PASSWORD=MAILLPASSWORD
    #  - GF_SMTP_FROM_ADDRESS=monitoring@yourdomain.tld
    #  - GF_RENDERING_SERVER_URL=http://renderer:8081/render
    #  - GF_RENDERING_CALLBACK_URL=http://grafana:3000/
    #  - GF_LOG_FILTERS=rendering:debug
    networks:
      - default

volumes:
  prometheus_data:
  grafana_data: